FROM jupyter/base-notebook

USER root

# instala Java
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean

# configura JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER $NB_UID